sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gonegitterdunn/docker-react -f Dockerfile.dev .

deploy:
  provider: elasticbeanstalk
  region:   "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-eu-west-1-xxxxxxxx"
  bucket-path: "docker"
  on:
    branch: master